; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:waveshare_esp32_s3_zero]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = waveshare_esp32_s3_zero
framework = espidf
lib_deps = 
	h2zero/esp-nimble-cpp@^2.5.0
build_flags = 
	-D HAS_LED_STRIP
	-D CONFIG_LOG_MAXIMUM_LEVEL=3
	-D USE_ESP_IDF_LOG
upload_port = COM3