idf_component_register( SRCS 
                            "VictronDevice.cpp"
                            "UploadDataClient.cpp"
                            "SdLogger.cpp"
                            "BleConnection.cpp"
                            "YRShellEsp32.cpp"
                            "main.cpp"
                            "AppManager.cpp"
                            "LedStripDriver.cpp"
                            "Utilities.cpp"
                            "WifiConnection.cpp"
                            "TelnetServer.cpp"
                            "SystemStatus.cpp"
                            "TempHumidityParser.cpp"
                            "Sen66Device.cpp"
                            "AdcDriver.cpp"
                        PRIV_REQUIRES
                            nvs_flash
                            spi_flash
                            esp_driver_rmt
                            esp_wifi
                            esp_driver_gpio
                            esp_driver_usb_serial_jtag
                            esp_adc
                            fatfs
                            sdmmc
                            mbedtls
                            esp_app_format
                            espUtilities
                            yrShell
                            sensirionI2C
                       INCLUDE_DIRS ".")
